manipulator:
  kinematics_solver: ur_kinematics/UR3KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
# ur_kinematics/UR3KinematicsPlugin
# kdl_kinematics_plugin/KDLKinematicsPlugin
# trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
